import {
  DeleteObjectCommand,
  HeadObjectCommand,
  PutObjectCommand,
  S3Client,
  GetObjectCommand,
  type S3ClientConfig,
} from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";
import { env } from "../../config/env.js";
import type {
  ObjectStorage,
  SignedDownloadRequest,
  SignedUploadRequest,
  SignedUrlResult,
  StoredObjectMetadata,
  StoredObjectWriteRequest,
} from "./storage.contract.js";

/** Builds the provider-neutral S3 client configuration from validated environment values. */
function buildClientConfig(): S3ClientConfig {
  return {
    region: env.STORAGE_REGION,
    ...(env.STORAGE_ENDPOINT ? { endpoint: env.STORAGE_ENDPOINT } : {}),
    forcePathStyle: env.STORAGE_FORCE_PATH_STYLE,
    ...(env.STORAGE_ACCESS_KEY_ID && env.STORAGE_SECRET_ACCESS_KEY
      ? {
          credentials: {
            accessKeyId: env.STORAGE_ACCESS_KEY_ID,
            secretAccessKey: env.STORAGE_SECRET_ACCESS_KEY,
          },
        }
      : {}),
  };
}

/** S3-compatible storage adapter supporting AWS S3, Cloudflare R2 and compatible providers. */
export class S3ObjectStorage implements ObjectStorage {
  private readonly client: S3Client;

  /** Stores the S3-compatible client and configured bucket used by this adapter. */
  constructor(
    client = new S3Client(buildClientConfig()),
    private readonly bucket = env.STORAGE_BUCKET,
  ) {
    this.client = client;
  }

  /** Creates a short-lived signed URL for one authorized direct upload. */
  async createSignedUpload(request: SignedUploadRequest): Promise<SignedUrlResult> {
    const expiresIn = request.expiresInSeconds ?? env.STORAGE_SIGNED_URL_TTL_SECONDS;
    const command = new PutObjectCommand({
      Bucket: this.bucket,
      Key: request.objectKey,
      ContentType: request.contentType,
      ...(request.contentLength !== undefined ? { ContentLength: request.contentLength } : {}),
    });

    return {
      url: await getSignedUrl(this.client, command, { expiresIn }),
      objectKey: request.objectKey,
      expiresAt: new Date(Date.now() + expiresIn * 1_000),
    };
  }

  /** Writes server-generated bytes to one server-controlled object key without exposing an upload URL. */
  async putObject(request: StoredObjectWriteRequest): Promise<StoredObjectMetadata> {
    const result = await this.client.send(
      new PutObjectCommand({
        Bucket: this.bucket,
        Key: request.objectKey,
        Body: request.body,
        ContentType: request.contentType,
        ContentLength: request.body.byteLength,
      }),
    );

    return {
      contentType: request.contentType,
      contentLength: request.body.byteLength,
      checksum: result.ChecksumSHA256 ?? null,
    };
  }

  /** Creates a short-lived signed URL for one authorized object download. */
  async createSignedDownload(request: SignedDownloadRequest): Promise<SignedUrlResult> {
    const expiresIn = request.expiresInSeconds ?? env.STORAGE_SIGNED_URL_TTL_SECONDS;
    const command = new GetObjectCommand({
      Bucket: this.bucket,
      Key: request.objectKey,
      ...(request.downloadFileName
        ? { ResponseContentDisposition: `attachment; filename="${request.downloadFileName.replace(/[\r\n"]/g, "")}"` }
        : {}),
    });

    return {
      url: await getSignedUrl(this.client, command, { expiresIn }),
      objectKey: request.objectKey,
      expiresAt: new Date(Date.now() + expiresIn * 1_000),
    };
  }

  /** Deletes one object by its server-controlled object key. */
  async deleteObject(objectKey: string): Promise<void> {
    await this.client.send(new DeleteObjectCommand({ Bucket: this.bucket, Key: objectKey }));
  }

  /** Reads provider-neutral object metadata without downloading object contents. */
  async getObjectMetadata(objectKey: string): Promise<StoredObjectMetadata | null> {
    try {
      const result = await this.client.send(
        new HeadObjectCommand({ Bucket: this.bucket, Key: objectKey }),
      );
      return {
        contentType: result.ContentType ?? null,
        contentLength: result.ContentLength ?? null,
        checksum: result.ChecksumSHA256 ?? null,
      };
    } catch (error) {
      const status = (error as { $metadata?: { httpStatusCode?: number } }).$metadata
        ?.httpStatusCode;
      if (status === 404) return null;
      throw error;
    }
  }

  /** Checks whether one object exists without downloading its contents. */
  async objectExists(objectKey: string): Promise<boolean> {
    return (await this.getObjectMetadata(objectKey)) !== null;
  }
}
